
/**
 * PDF export functionality with comprehensive analytics
 */
import { toast } from "sonner";
import { generateAnalytics } from './analyticsGenerator';
import { downloadFile } from './fileDownloader';
import { ExportData } from './types';

/**
 * Export data to PDF format with comprehensive analytics and beautiful formatting
 * @param data Data to export
 * @param title Title of the document
 * @param formatCurrency Function to format currency values
 */
export const exportToPdf = (data: ExportData, title: string, formatCurrency?: (amount: number) => string) => {
  console.log('Exporting comprehensive analytics to PDF:', { data, title });
  
  try {
    // Generate comprehensive analytics
    const analytics = generateAnalytics(data, formatCurrency);
    
    // Create beautifully formatted PDF content with analytics
    const pdfContent = `%PDF-1.5
1 0 obj
<</Type /Catalog /Pages 2 0 R>>
endobj
2 0 obj
<</Type /Pages /Kids [3 0 R 4 0 R 5 0 R 6 0 R] /Count 4>>
endobj
3 0 obj
<</Type /Page /Parent 2 0 R /Resources 7 0 R /MediaBox [0 0 612 792] /Contents 8 0 R>>
endobj
4 0 obj
<</Type /Page /Parent 2 0 R /Resources 7 0 R /MediaBox [0 0 612 792] /Contents 9 0 R>>
endobj
5 0 obj
<</Type /Page /Parent 2 0 R /Resources 7 0 R /MediaBox [0 0 612 792] /Contents 10 0 R>>
endobj
6 0 obj
<</Type /Page /Parent 2 0 R /Resources 7 0 R /MediaBox [0 0 612 792] /Contents 11 0 R>>
endobj
7 0 obj
<</Font <</F1 12 0 R /F2 13 0 R /F3 14 0 R>>>>
endobj
8 0 obj
<</Length 1200>>
stream
BT
/F1 24 Tf
50 720 Td
(${title}) Tj
/F2 12 Tf
0 -30 Td
(Generated: ${new Date().toLocaleDateString()}) Tj
0 -20 Td
(Currency: ${analytics.currency}) Tj
0 -50 Td
/F1 18 Tf
(EXECUTIVE SUMMARY) Tj
/F2 12 Tf
0 -30 Td
(Financial Health Score: ${analytics.healthScore}/100) Tj
0 -20 Td
(Total Income: ${analytics.formattedIncome}) Tj
0 -15 Td
(Total Expenses: ${analytics.formattedExpenses}) Tj
0 -15 Td
(Net Savings: ${analytics.formattedSavings}) Tj
0 -15 Td
(Savings Rate: ${analytics.savingsRate}%) Tj
0 -15 Td
(Risk Assessment: ${analytics.riskLevel}) Tj
0 -40 Td
/F1 16 Tf
(KEY PERFORMANCE INDICATORS) Tj
/F2 10 Tf
0 -25 Td
(Monthly Growth Rate: ${analytics.monthlyGrowth}%) Tj
0 -15 Td
(Best Income Month: ${analytics.bestIncomeMonth}) Tj
0 -15 Td
(Highest Expense Month: ${analytics.worstExpenseMonth}) Tj
0 -15 Td
(Category Diversity: ${analytics.categoryDiversity} categories) Tj
0 -15 Td
(Projected 6-Month Savings: ${analytics.formattedProjectedSavings}) Tj
ET
endstream
endobj
9 0 obj
<</Length 800>>
stream
BT
/F1 18 Tf
50 720 Td
(DETAILED FINANCIAL ANALYSIS) Tj
/F2 12 Tf
0 -40 Td
(Monthly Income vs Expenses Breakdown:) Tj
/F3 10 Tf
${analytics.monthlyBreakdown}
/F2 12 Tf
0 -120 Td
(Expense Categories Analysis:) Tj
/F3 10 Tf
${analytics.categoryAnalysis}
/F2 12 Tf
0 -80 Td
(Largest Expense Category: ${analytics.largestCategory}) Tj
0 -15 Td
(Average Monthly Net: ${analytics.formattedAvgMonthlyNet}) Tj
ET
endstream
endobj
10 0 obj
<</Length 600>>
stream
BT
/F1 18 Tf
50 720 Td
(RECOMMENDATIONS & INSIGHTS) Tj
/F2 12 Tf
0 -40 Td
(Priority Recommendations:) Tj
/F3 10 Tf
${analytics.recommendations}
/F2 12 Tf
0 -120 Td
(Financial Optimization Opportunities:) Tj
/F3 10 Tf
0 -20 Td
(• Expense Optimization Potential: ${analytics.optimizationPotential}) Tj
0 -15 Td
(• Recommended Emergency Fund: ${analytics.formattedEmergencyFund}) Tj
0 -15 Td
(• Investment Readiness Score: ${analytics.investmentScore}/10) Tj
ET
endstream
endobj
11 0 obj
<</Length 400>>
stream
BT
/F1 18 Tf
50 720 Td
(FINANCIAL PROJECTIONS) Tj
/F2 12 Tf
0 -40 Td
(12-Month Financial Forecast:) Tj
/F3 10 Tf
0 -25 Td
(Projected Annual Income: ${analytics.formattedProjectedIncome}) Tj
0 -15 Td
(Projected Annual Expenses: ${analytics.formattedProjectedExpenses}) Tj
0 -15 Td
(Projected Annual Savings: ${analytics.formattedProjectedAnnualSavings}) Tj
0 -30 Td
/F2 12 Tf
(Report Summary:) Tj
/F3 10 Tf
0 -20 Td
(This comprehensive financial report provides detailed) Tj
0 -15 Td
(analysis of your financial performance with actionable) Tj
0 -15 Td
(insights and recommendations for optimization.) Tj
0 -30 Td
(Generated by Financial Analytics Suite) Tj
0 -30 Td
/F2 10 Tf
(APPENDIX: Currency values are displayed as entered.) Tj
0 -15 Td
(No exchange rate conversions are applied.) Tj
0 -15 Td
(Multi-currency data reflects nominal amounts only.) Tj
ET
endstream
endobj
12 0 obj
<</Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold>>
endobj
13 0 obj
<</Type /Font /Subtype /Type1 /BaseFont /Helvetica>>
endobj
14 0 obj
<</Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique>>
endobj
xref
0 15
0000000000 65535 f
0000000009 00000 n
0000000056 00000 n
0000000125 00000 n
0000000226 00000 n
0000000327 00000 n
0000000428 00000 n
0000000529 00000 n
0000000594 00000 n
0000001850 00000 n
0000002700 00000 n
0000003350 00000 n
0000003800 00000 n
0000003865 00000 n
0000003928 00000 n
trailer
<</Size 15 /Root 1 0 R>>
startxref
3998
%%EOF
`;
    
    const blob = new Blob([pdfContent], { type: 'application/pdf' });
    downloadFile(blob, `Comprehensive_Financial_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    toast.success("Comprehensive financial analytics report exported successfully!");
  } catch (error) {
    console.error("PDF Export failed:", error);
    toast.error("Failed to export PDF report");
  }
};
