import { toast } from "sonner";
import { downloadFile, downloadCSV, downloadTextFile } from "./fileDownloader";
import type { SummaryRow } from "@/components/Analytics/AnalyticsSummaryTable";

interface SummaryExportData {
  rows: SummaryRow[];
  totalIncome: number;
  totalExpense: number;
  startDate: string;
  endDate: string;
}

export function exportSummaryToPdf(
  data: SummaryExportData,
  formatCurrency: (amount: number) => string
) {
  try {
    const { rows, totalIncome, totalExpense, startDate, endDate } = data;
    const balance = totalIncome - totalExpense;

    // Create PDF-like content as formatted text
    let content = `INCOME & EXPENSES SUMMARY REPORT\n`;
    content += `${"=".repeat(80)}\n\n`;
    content += `Period: ${startDate} - ${endDate}\n`;
    content += `Generated: ${new Date().toLocaleString()}\n\n`;
    content += `${"=".repeat(80)}\n\n`;

    // Summary section at top
    content += `SUMMARY\n`;
    content += `${"-".repeat(40)}\n`;
    content += `Total Income:      ${formatCurrency(totalIncome)}\n`;
    content += `Total Expenses:    ${formatCurrency(totalExpense)}\n`;
    content += `Net Balance:       ${formatCurrency(balance)}\n`;
    content += `Transactions:      ${rows.length}\n\n`;
    content += `${"=".repeat(80)}\n\n`;

    // Table header
    content += `TRANSACTION DETAILS\n`;
    content += `${"-".repeat(80)}\n`;
    content += `${"Date".padEnd(14)} ${"Description".padEnd(25)} ${"Category".padEnd(18)} ${"Income".padStart(12)} ${"Expense".padStart(12)}\n`;
    content += `${"-".repeat(80)}\n`;

    // Table rows
    if (rows.length === 0) {
      content += `No transactions found for this period.\n`;
    } else {
      rows.forEach((row) => {
        const date = (row.date || "").padEnd(14).substring(0, 14);
        const desc = (row.description || "No description").padEnd(25).substring(0, 25);
        const cat = (row.category || "Uncategorized").padEnd(18).substring(0, 18);
        const inc = row.income > 0 ? formatCurrency(row.income).padStart(12) : "-".padStart(12);
        const exp = row.expense > 0 ? formatCurrency(row.expense).padStart(12) : "-".padStart(12);
        content += `${date} ${desc} ${cat} ${inc} ${exp}\n`;
      });
    }

    // Footer
    content += `${"-".repeat(80)}\n`;
    content += `${"TOTALS".padEnd(57)} ${formatCurrency(totalIncome).padStart(12)} ${formatCurrency(totalExpense).padStart(12)}\n`;
    content += `${"=".repeat(80)}\n\n`;

    content += `Note: Currency values are displayed as entered. No exchange rate conversions applied.\n`;
    content += `Report generated by ExpenseCoin Finance Tracker\n`;

    // Create safe filename
    const safeStartDate = startDate.replace(/[^a-zA-Z0-9-]/g, '');
    const safeEndDate = endDate.replace(/[^a-zA-Z0-9-]/g, '');
    const filename = `ExpenseCoin-Report-${safeStartDate}-to-${safeEndDate}.txt`;
    
    const success = downloadTextFile(content, filename, 'text/plain');
    
    if (success) {
      toast.success("Report exported successfully as text file");
    } else {
      toast.error("Failed to download report. Please try again.");
    }
  } catch (error) {
    console.error("Export to PDF failed:", error);
    toast.error("Failed to export report. Please try again.");
  }
}

export function exportSummaryToExcel(
  data: SummaryExportData,
  formatCurrency: (amount: number) => string
) {
  try {
    const { rows, totalIncome, totalExpense, startDate, endDate } = data;
    const balance = totalIncome - totalExpense;

    // Create CSV content with proper escaping
    let csv = `Income & Expenses Summary Report\n`;
    csv += `Period,"${startDate} - ${endDate}"\n`;
    csv += `Generated,"${new Date().toLocaleString()}"\n`;
    csv += `\n`;

    // Summary
    csv += `Summary\n`;
    csv += `Total Income,"${formatCurrency(totalIncome)}"\n`;
    csv += `Total Expenses,"${formatCurrency(totalExpense)}"\n`;
    csv += `Net Balance,"${formatCurrency(balance)}"\n`;
    csv += `Number of Transactions,${rows.length}\n`;
    csv += `\n`;

    // Header - this exact format is expected by the import function
    csv += `Date,Description,Category,Income,Expense\n`;

    // Data rows with proper CSV escaping
    if (rows.length === 0) {
      csv += `No transactions found for this period,,,\n`;
    } else {
      rows.forEach((row) => {
        const date = row.date || "";
        const desc = `"${(row.description || "").replace(/"/g, '""')}"`;
        const cat = `"${(row.category || "").replace(/"/g, '""')}"`;
        const inc = row.income > 0 ? row.income.toString() : "";
        const exp = row.expense > 0 ? row.expense.toString() : "";
        csv += `${date},${desc},${cat},${inc},${exp}\n`;
      });
    }

    // Totals
    csv += `\n`;
    csv += `TOTAL,,,${totalIncome},${totalExpense}\n`;
    csv += `BALANCE,,,${balance},\n`;

    // Create safe filename
    const safeStartDate = startDate.replace(/[^a-zA-Z0-9-]/g, '');
    const safeEndDate = endDate.replace(/[^a-zA-Z0-9-]/g, '');
    const filename = `ExpenseCoin-Report-${safeStartDate}-to-${safeEndDate}.csv`;
    
    const success = downloadCSV(csv, filename);
    
    if (success) {
      toast.success("CSV report exported successfully");
    } else {
      toast.error("Failed to download CSV. Please try again.");
    }
  } catch (error) {
    console.error("Export to Excel failed:", error);
    toast.error("Failed to export CSV report. Please try again.");
  }
}
